### ISSUE TITLE
Vérifier cyrillic et grec

### ISSUE THREAD

**Issue by jeanbaptistedeborman** [jeanbaptistedeborman/buglistBudgetAtAGlance#107]

**Comment by Fgrelet** [comment]
J'en suis à 19 emails
C'est un plaisir.
:)

**Comment by jeanbaptistedeborman** [comment]
Comme ça tu sais que ton consultant travaille. Perso, j'aime bien que tu suives mon travail. Je trouve que tu es un bon manager.
